# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptechapp', '0002_auto_20190326_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='languages',
            field=models.CharField(default='English', max_length=255),
        ),
    ]
