# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aptechapp', '0003_branch_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='batch_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aptechapp.Branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roll_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
