# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptechapp', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='languages',
            field=models.TextField(choices=[('Afrikaans', 'Afrikaans'), ('Amharic', 'Amharic'), ('Arabic', 'Arabic'), ('Azerbaijani', 'Azerbaijani'), ('Belarusian', 'Belarusian'), ('Bulgarian', 'Bulgarian'), ('Bengali', 'Bengali'), ('Bosnian', 'Bosnian'), ('Catalan', 'Catalan'), ('Cebuano', 'Cebuano'), ('Corsican', 'Corsican'), ('Czech', 'Czech'), ('Welsh', 'Welsh'), ('Danish', 'Danish'), ('German', 'German'), ('Greek', 'Greek'), ('English', 'English'), ('Esperanto', 'Esperanto'), ('Spanish', 'Spanish'), ('Estonian', 'Estonian'), ('Basque', 'Basque'), ('Persian', 'Persian'), ('Finnish', 'Finnish'), ('French', 'French'), ('Frisian', 'Frisian'), ('Irish', 'Irish'), ('Scots Gaelic', 'Scots Gaelic'), ('Galician', 'Galician'), ('Gujarati', 'Gujarati'), ('Hausa', 'Hausa'), ('Hawaiian', 'Hawaiian'), ('Hindi', 'Hindi'), ('Hmong', 'Hmong'), ('Croatian', 'Croatian'), ('Haitian Creole', 'Haitian Creole'), ('Hungarian', 'Hungarian'), ('Armenian', 'Armenian'), ('Indonesian', 'Indonesian'), ('Igbo', 'Igbo'), ('Icelandic', 'Icelandic'), ('Italian', 'Italian'), ('Hebrew', 'Hebrew '), ('Japanese', 'Japanese'), ('Javanese', 'Javanese'), ('Georgian', 'Georgian'), ('Kazakh', 'Kazakh'), ('Khmer', 'Khmer'), ('Kannada', 'Kannada'), ('Korean', 'Korean'), ('Kurdish', 'Kurdish'), ('Kyrgyz', 'Kyrgyz'), ('Latin', 'Latin'), ('Luxembourgish', 'Luxembourgish'), ('Lao', 'Lao'), ('Lithuanian', 'Lithuanian'), ('Latvian', 'Latvian'), ('Malagasy', 'Malagasy'), ('Maori', 'Maori'), ('Macedonian', 'Macedonian'), ('Malayalam', 'Malayalam'), ('Mongolian', 'Mongolian'), ('Marathi', 'Marathi'), ('Malay', 'Malay'), ('Maltese', 'Maltese'), ('Myanmar (Burmese)', 'Myanmar (Burmese)'), ('Nepali', 'Nepali'), ('Dutch', 'Dutch'), ('Norwegian', 'Norwegian'), ('Nyanja (Chichewa)', 'Nyanja (Chichewa)'), ('Punjabi', 'Punjabi'), ('Polish', 'Polish'), ('Pashto', 'Pashto'), ('Portuguese (Portugal, Brazil)', 'Portuguese (Portugal, Brazil)'), ('Romanian', 'Romanian'), ('Russian', 'Russian'), ('Sindhi', 'Sindhi'), ('Sinhala (Sinhalese)', 'Sinhala (Sinhalese)'), ('Slovak', 'Slovak'), ('Slovenian', 'Slovenian'), ('Samoan', 'Samoan'), ('Shona', 'Shona'), ('Somali', 'Somali'), ('Albanian', 'Albanian'), ('Serbian', 'Serbian'), ('Sesotho', 'Sesotho'), ('Sundanese', 'Sundanese'), ('Swedish', 'Swedish'), ('Swahili', 'Swahili'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Tajik', 'Tajik'), ('Thai', 'Thai'), ('Tagalog (Filipino)', 'Tagalog (Filipino)'), ('Turkish', 'Turkish'), ('Ukrainian', 'Ukrainian'), ('Urdu', 'Urdu'), ('Uzbek', 'Uzbek'), ('Vietnamese', 'Vietnamese'), ('Xhosa', 'Xhosa'), ('Yiddish', 'Yiddish'), ('Yoruba', 'Yoruba'), ('Chinese', 'Chinese'), ('Chinese', 'Chinese'), ('Zulu', 'Zulu')], default='English', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='roll_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
