# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptechapp', '0009_auto_20190329_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
