# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptechapp', '0010_remove_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='book_link',
        ),
        migrations.RemoveField(
            model_name='library',
            name='is_link',
        ),
    ]
